# Release: https://github.com/scrtlabs/fetchai-agent-template/releases/tag/v0.0.4
# Workflow URL: https://github.com/scrtlabs/fetchai-agent-template/actions/runs/15953101358
# Commit: https://github.com/scrtlabs/fetchai-agent-template/commit/3a23cdf870d9d8a54c004d9cbb2b9d99e945db34
version: '3'
services:
  app:
    image: ghcr.io/scrtlabs/fetchai-agent-template@sha256:228e98476a07f2f55e2193e8a3249828c30c247347d5f4d0c41733f112ede056
    ports:
      - '8000:80'
