# Release: https://github.com/scrtlabs/fetchai-agent-template/releases/tag/v0.0.1
# Workflow URL: https://github.com/scrtlabs/fetchai-agent-template/actions/runs/15927731582
# Commit: https://github.com/scrtlabs/fetchai-agent-template/commit/4b617196f3cf3b197aa5d75abca8059f10b7a1cd
version: '3'
services:
  app:
    image: ghcr.io/scrtlabs/fetchai-agent-template@sha256:d43751f5790d1d5cbc65f51c132208af5c406d327ccc5c7bac905f3e3589892b
    ports:
      - '8000:80'
