# Release: https://github.com/scrtlabs/fetchai-agent-template/releases/tag/v0.0.5
# Workflow URL: https://github.com/scrtlabs/fetchai-agent-template/actions/runs/15953383411
# Commit: https://github.com/scrtlabs/fetchai-agent-template/commit/5017b0217df54fbf641e18f1c749ee8f1236d2d2
version: '3'
services:
  app:
    image: ghcr.io/scrtlabs/fetchai-agent-template@sha256:db88d7d1936eb33a3f5aff63136b51c175c4a08ff9d9a1ac52313014ebc4853b
    ports:
      - '8000:8000'
