# Release: https://github.com/scrtlabs/fetchai-agent-template/releases/tag/v0.0.3
# Workflow URL: https://github.com/scrtlabs/fetchai-agent-template/actions/runs/15952863963
# Commit: https://github.com/scrtlabs/fetchai-agent-template/commit/3b8edce19c73cf49e2eaf3c6d7045f9b0817127a
version: '3'
services:
  app:
    image: ghcr.io/scrtlabs/fetchai-agent-template@sha256:e0726ce68e274be478d4160e82af0aac851b25495f3dc56531db9c4535ebf043
    ports:
      - '8000:8000'
