# Release: https://github.com/scrtlabs/fetchai-agent-template/releases/tag/v0.0.2
# Workflow URL: https://github.com/scrtlabs/fetchai-agent-template/actions/runs/15952828303
# Commit: https://github.com/scrtlabs/fetchai-agent-template/commit/171c90f4f42a880f0e91412e9eb124c73259cd49
version: '3'
services:
  app:
    image: ghcr.io/scrtlabs/fetchai-agent-template@sha256:b0648b123e3ee6af037041595653d51151d32d67de38866b51cff1d85f1c551e
    ports:
      - '8000:80'
